server:
  port: 8080
  compression:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webflux_tutorial
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create